# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin mkdocs-offline pymdown-extensions

mkdocs:
  configuration: mkdocs.yml

formats:
  - htmlzip
  - pdf
  - epub