# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen    
    - graphviz
  jobs:
    pre_build:
      # Doxygen XML 생성 -> Breath -> Sphinx 
      - doxygen Doxyfile_sphinx  
      - ls -alh docs/_doxygen   # raw log 확인
      - ls -alh docs/_doxygen/xml # raw log 확인    
      - ls -alh docs/_doxygen/html # raw log 확인           
    post_install:
      - pip install -r docs/sphinx_requirements.txt
  
sphinx:
  configuration: docs/conf.py   # Sphinx 설정 파일 위치

formats:
  - htmlzip
  - pdf
  - epub