# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - doxygen    
  jobs:
    pre_build:
      - doxygen Doxyfile  
    post_install:
      - pip install -r docs/readthedoc_requirements.txt
  
mkdocs:
  configuration: mkdocs.yml

formats:
  - htmlzip
  - pdf
  - epub